---

- hosts: all
  become: yes
  tasks:

  - name: Install repo
    get_url: 
      url: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu20.04_all.deb
      dest: /home/neold
      force_basic_auth: yes
  - name: Check if zabbix_package is installed
    command: dpkg -i zabbix-release_6.0-4+ubuntu20.04_all.deb

  -  name: Install zabbix_agent2 on Debian Family
     apt:
        name=zabbix-agent2
        state=latest
     when:
        ansible_os_family == "Debian"
        
  - name: Edit config
    replace:
      path: /etc/zabbix/zabbix_agent2.conf
      regexp: 'Server=127.0.0.1'
      replace: 'Server=130.193.55.241'

- hosts: ubuntu2
  become: yes
  tasks:

    - name: Edit config
      replace:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: 'Hostname=Zabbix server'
        replace: 'Hostname=Ubuntu2'

- hosts: ubuntu3
  become: yes
  tasks:

    - name: Edit config
      replace:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: 'Hostname=Zabbix server'
        replace: 'Hostname=Ubuntu3'

- hosts: all
  become: yes  
  handlers:
  - name: zabbix-agent2 systemd
    systemd:
     name: zabbix-agent2
     enabled: yes
     state: started
